# x = input("...")
# print(x)
# print(int(x))
# print(type(int(x)))
# print(float(x))
# print(type(float(x)))
# print(f"{tuple(x)}")
# print(type(tuple(x)))

ev = eval(input("eval..."))
print(type(ev))